"""
This output is based off the file called 'testedscholarlymodule2.py' FROM folder 'iterations of scholarly module'... it also uses the sample data file called 'keywords_authors_years.csv' FROM folder 'sample data files used'
"""
(base) tanushkaushik@Tanushs-MacBook-Pro Texas Lead DS % python3 testedscholarlymodule2.py
krishna kumar 2023 curriculum
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Liberalisation, privatisation, modernisation, and schooling in India: An interview with Krishna Kumar', 'author': ['C LaDousa'], 'pub_year': '2007', 'venue': 'Globalisation, Societies and Education', 'abstract': 'In 2004, India’s Congress Party wrested control of parliament from the Hindu nationalist  Bharatiya Janata Party. I present below an interview conducted with Professor Krishna Kumar,'}, 'filled': False, 'gsrank': 1, 'pub_url': 'https://www.tandfonline.com/doi/abs/10.1080/14767720701425628', 'author_id': ['cPY2hPIAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:p1A1yltMh2AJ:scholar.google.com/&output=cite&scirp=0&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dkrishna%2Bkumar%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=p1A1yltMh2AJ&ei=jIRoZtiSBNS-6rQP_NO1gAc&json=', 'num_citations': 31, 'citedby_url': '/scholar?cites=6955612106615247015&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:p1A1yltMh2AJ:scholar.google.com/&scioq=krishna+kumar+2023+curriculum&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Technology and Education Today', 'author': ['K Kumar'], 'pub_year': '2022', 'venue': 'Social Change', 'abstract': 'as a scripted curriculum, a modular lesson, a PowerPoint presentation or any number of  ever-increasing conveniences. The new commonplace of curriculum includes the replacement'}, 'filled': False, 'gsrank': 2, 'pub_url': 'https://journals.sagepub.com/doi/abs/10.1177/00490857221134925', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:NvjFxqfYC-UJ:scholar.google.com/&output=cite&scirp=1&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dkrishna%2Bkumar%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=NvjFxqfYC-UJ&ei=jIRoZtiSBNS-6rQP_NO1gAc&json=', 'num_citations': 2, 'citedby_url': '/scholar?cites=16504523474535315510&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:NvjFxqfYC-UJ:scholar.google.com/&scioq=krishna+kumar+2023+curriculum&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Human and integral education: educational paradigms from the Indian context expanding meanings of peace and conflict', 'author': ['K Kumar'], 'pub_year': '2022', 'venue': 'Journal of Peace Education', 'abstract': 'Consequently, school curriculum has played a role in  For instance, the Indian national peace  curriculum draws our attention  The national peace curriculum also recognizes exclusion in'}, 'filled': False, 'gsrank': 3, 'pub_url': 'https://www.tandfonline.com/doi/abs/10.1080/17400201.2022.2148639', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:m6pksJmNLowJ:scholar.google.com/&output=cite&scirp=2&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dkrishna%2Bkumar%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=m6pksJmNLowJ&ei=jIRoZtiSBNS-6rQP_NO1gAc&json=', 'num_citations': 3, 'citedby_url': '/scholar?cites=10101166705467501211&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:m6pksJmNLowJ:scholar.google.com/&scioq=krishna+kumar+2023+curriculum&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Empowering Minds: The Evolution of Higher Education in Tamil Nadu towards Innovation and Excellence', 'author': ['A Saravanakumar', 'K Krishnamoorthy'], 'pub_year': '2023', 'venue': 'NA', 'abstract': "are clearly outlined in the State's Vision 2023. The vision document declares the government's   development goals in curriculum, research, innovation, cocurricular, and extracurricular"}, 'filled': False, 'gsrank': 4, 'pub_url': 'https://www.researchgate.net/profile/Dr-saravanakumar-2/publication/374673790_The_Evolution_of_Higher_Education_in_Tamil_Nadu_towards_Innovation_and_Excellence/links/6528d1062e1ba453041e6c26/The-Evolution-of-Higher-Education-in-Tamil-Nadu-towards-Innovation-and-Excellence.pdf', 'author_id': ['3gl8pgIAAAAJ', 'teFhC08AAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:ux3yW6jCHCMJ:scholar.google.com/&output=cite&scirp=3&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dkrishna%2Bkumar%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=ux3yW6jCHCMJ&ei=jIRoZtiSBNS-6rQP_NO1gAc&json=', 'num_citations': 1, 'citedby_url': '/scholar?cites=2530111119028264379&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:ux3yW6jCHCMJ:scholar.google.com/&scioq=krishna+kumar+2023+curriculum&hl=en&as_sdt=0,33', 'eprint_url': 'https://www.researchgate.net/profile/Dr-saravanakumar-2/publication/374673790_The_Evolution_of_Higher_Education_in_Tamil_Nadu_towards_Innovation_and_Excellence/links/6528d1062e1ba453041e6c26/The-Evolution-of-Higher-Education-in-Tamil-Nadu-towards-Innovation-and-Excellence.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Reflections on Teaching an Engineering Course through Murder Mysteries.', 'author': ['K Kumar'], 'pub_year': '2023', 'venue': 'Journal of Technology and Science Education', 'abstract': 'This paper presents a reflective analysis of a novel approach to Problem-Based Learning (PBL)  to teach abstract concepts in a large-class setting, specifically tailored for a third-year'}, 'filled': False, 'gsrank': 5, 'pub_url': 'https://eric.ed.gov/?id=EJ1407522', 'author_id': ['VJQEa68AAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:UE5Ej0rVoXcJ:scholar.google.com/&output=cite&scirp=4&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dkrishna%2Bkumar%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=UE5Ej0rVoXcJ&ei=jIRoZtiSBNS-6rQP_NO1gAc&json=', 'num_citations': 1, 'citedby_url': '/scholar?cites=8620405677971754576&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:UE5Ej0rVoXcJ:scholar.google.com/&scioq=krishna+kumar+2023+curriculum&hl=en&as_sdt=0,33', 'eprint_url': 'https://files.eric.ed.gov/fulltext/EJ1407522.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Developmental challenges to internationalizing the higher education sector: a critical inquiry of business schools in Kerala', 'author': ['KT John', 'KS Kumar'], 'pub_year': '2023', 'venue': 'Rajagiri Management Journal', 'abstract': "Purpose Kerala is one of India's most advanced states in human development and other  social indices. This study aims to look at the management education scenario in Kerala from a"}, 'filled': False, 'gsrank': 6, 'pub_url': 'https://www.emerald.com/insight/content/doi/10.1108/RAMJ-07-2021-0058/full/html', 'author_id': ['E9IMsvoAAAAJ', ''], 'url_scholarbib': '/scholar?hl=en&q=info:Av3ZWD5FGA8J:scholar.google.com/&output=cite&scirp=5&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dkrishna%2Bkumar%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=Av3ZWD5FGA8J&ei=jIRoZtiSBNS-6rQP_NO1gAc&json=', 'num_citations': 5, 'citedby_url': '/scholar?cites=1087695444090944770&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:Av3ZWD5FGA8J:scholar.google.com/&scioq=krishna+kumar+2023+curriculum&hl=en&as_sdt=0,33', 'eprint_url': 'https://www.emerald.com/insight/content/doi/10.1108/RAMJ-07-2021-0058/full/html'}
[{'title': 'Reflections on Teaching an Engineering Course through Murder Mysteries.', 'author': ['K Kumar'], 'year': '2023', 'abstract': 'This paper presents a reflective analysis of a novel approach to Problem-Based Learning (PBL)  to teach abstract concepts in a large-class setting, specifically tailored for a third-year', 'url': 'https://files.eric.ed.gov/fulltext/EJ1407522.pdf'}]
[{'title': 'Reflections on Teaching an Engineering Course through Murder Mysteries.', 'author': ['K Kumar'], 'year': '2023', 'abstract': 'This paper presents a reflective analysis of a novel approach to Problem-Based Learning (PBL)  to teach abstract concepts in a large-class setting, specifically tailored for a third-year', 'url': 'https://files.eric.ed.gov/fulltext/EJ1407522.pdf'}, {'title': 'Developmental challenges to internationalizing the higher education sector: a critical inquiry of business schools in Kerala', 'author': ['KT John', 'KS Kumar'], 'year': '2023', 'abstract': "Purpose Kerala is one of India's most advanced states in human development and other  social indices. This study aims to look at the management education scenario in Kerala from a", 'url': 'https://www.emerald.com/insight/content/doi/10.1108/RAMJ-07-2021-0058/full/html'}]
jules elkins 2023 education
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
jules elkins 2023 student
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Stand our ground: The street justice of urban American riots, 1900 to 1968', 'author': ['A Elkins'], 'pub_year': '2016', 'venue': 'NA', 'abstract': 'Around 11 pm, on July 23, 1900, a hot, sticky New Orleans night, a white man reported “two  suspicious looking negroes” to a white police sergeant named Jules C. Aucoin (p. 119).'}, 'filled': False, 'gsrank': 1, 'pub_url': 'https://journals.sagepub.com/doi/abs/10.1177/0096144215623490', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:ie0G_5vZqBAJ:scholar.google.com/&output=cite&scirp=0&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=ie0G_5vZqBAJ&ei=z4RoZtTAJtS-6rQP_NO1gAc&json=', 'num_citations': 7, 'citedby_url': '/scholar?cites=1200448564716039561&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:ie0G_5vZqBAJ:scholar.google.com/&scioq=jules+elkins+2023+student&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Theatre History Studies 2022, Vol 41', 'author': ['L Milner', 'M Chapman', 'CE Mohler', 'T Boffone'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'in Colombia, teaching and mentoring theatre students who have spent the last three semesters   I was fortunate to be a student of the late Dr. Herbert Blau. He would fiercely remind us, in'}, 'filled': False, 'gsrank': 2, 'pub_url': 'https://books.google.com/books?hl=en&lr=&id=WLmeEAAAQBAJ&oi=fnd&pg=PR5&dq=jules+elkins+2023+student&ots=kdEb6a1_CC&sig=NcrfBGAPUqiI36g-pcf38YfvJ0Y', 'author_id': ['phYOjuYAAAAJ', 'zx9TiqEAAAAJ', '', 'wzEFYLgAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:7ki1egvOaqsJ:scholar.google.com/&output=cite&scirp=1&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=7ki1egvOaqsJ&ei=z4RoZtTAJtS-6rQP_NO1gAc&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:7ki1egvOaqsJ:scholar.google.com/&scioq=jules+elkins+2023+student&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Journey to a metal world', 'author': ['BP Weiss', 'LT Elkins-Tanton'], 'pub_year': '2024', 'venue': 'Physics Today', 'abstract': 'Jules Verne almost had it right back in 1864. In Journey to the Center of the Earth, a geologist  and his team descend into a volcano in Iceland to explore Earth’s hidden metal core. But it'}, 'filled': False, 'gsrank': 3, 'pub_url': 'https://pubs.aip.org/physicstoday/article/77/5/54/3283593', 'author_id': ['E5z9ToMAAAAJ', 'sODCFRQAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:qSxZJRtT7GAJ:scholar.google.com/&output=cite&scirp=2&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=qSxZJRtT7GAJ&ei=z4RoZtTAJtS-6rQP_NO1gAc&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:qSxZJRtT7GAJ:scholar.google.com/&scioq=jules+elkins+2023+student&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'The emergence of the English art school system', 'author': ['M Powell'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'A pleasingly large number of my students have gone onto rewarding careers, several of  ,  and liaised closely with industry to ensure students are capable of entering and contributing to'}, 'filled': False, 'gsrank': 4, 'pub_url': 'https://etheses.whiterose.ac.uk/33791/', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:D0jGr0YEIPUJ:scholar.google.com/&output=cite&scirp=3&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=D0jGr0YEIPUJ&ei=z4RoZtTAJtS-6rQP_NO1gAc&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:D0jGr0YEIPUJ:scholar.google.com/&scioq=jules+elkins+2023+student&hl=en&as_sdt=0,33', 'eprint_url': 'https://etheses.whiterose.ac.uk/33791/1/The%20emergence%20of%20the%20English%20art%20school.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Youth drug use in Barbados and England: Correlates with online peer influences', 'author': ['MA Jules', 'DMB Maynard'], 'pub_year': '2021', 'venue': 'Journal of adolescent …', 'abstract': 'employed with samples of students of African- students in Barbados and 186 in England.  Qualitative focus groups were conducted with 23 Barbadian students and 16 English students.'}, 'filled': False, 'gsrank': 5, 'pub_url': 'https://journals.sagepub.com/doi/abs/10.1177/0743558419839226', 'author_id': ['9MyCwfkAAAAJ', 'vPsyUv0AAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:BYNWC7YGvx4J:scholar.google.com/&output=cite&scirp=4&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=BYNWC7YGvx4J&ei=z4RoZtTAJtS-6rQP_NO1gAc&json=', 'num_citations': 5, 'citedby_url': '/scholar?cites=2215496920633606917&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:BYNWC7YGvx4J:scholar.google.com/&scioq=jules+elkins+2023+student&hl=en&as_sdt=0,33', 'eprint_url': 'https://nottingham-repository.worktribe.com/OutputFile/2032288'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Jewish American Writers and the J-Word', 'author': ['J Karp'], 'pub_year': '2023', 'venue': 'NA', 'abstract': '“I told Elizabeth Smith [owner of the farmhouse where the Elkins  Elkin can do is to lean  forward and say “But we are Jewish.”  Currently, university students are asking their instructors if'}, 'filled': False, 'gsrank': 6, 'pub_url': 'https://muse.jhu.edu/pub/60/oa_monograph/chapter/3787156', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:79MDXBve95YJ:scholar.google.com/&output=cite&scirp=5&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=79MDXBve95YJ&ei=z4RoZtTAJtS-6rQP_NO1gAc&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:79MDXBve95YJ:scholar.google.com/&scioq=jules+elkins+2023+student&hl=en&as_sdt=0,33', 'eprint_url': 'https://muse.jhu.edu/pub/60/oa_monograph/chapter/3787156'}
jules elkins 2023 classroom
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
jules elkins 2023 curriculum
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'The emergence of the English art school system', 'author': ['M Powell'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'This thesis deploys a Foucauldian genealogy to critique the historical emergence of the  English art school system. The first part considers the ancient values that transform the idea of'}, 'filled': False, 'gsrank': 1, 'pub_url': 'https://etheses.whiterose.ac.uk/33791/', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:D0jGr0YEIPUJ:scholar.google.com/&output=cite&scirp=0&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=D0jGr0YEIPUJ&ei=DIVoZuWOGLqY6rQP7_eJmAo&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:D0jGr0YEIPUJ:scholar.google.com/&scioq=jules+elkins+2023+curriculum&hl=en&as_sdt=0,33', 'eprint_url': 'https://etheses.whiterose.ac.uk/33791/1/The%20emergence%20of%20the%20English%20art%20school.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Using a Narrative Pedagogy to Incorporating Skills and Values in Legal Education: A Case for Moving Narrative Pedagogy from the Margin to the Centre', 'author': ['OF Emiri', 'E Aluta', 'C Lloyd'], 'pub_year': '2023', 'venue': 'KNUST LJ', 'abstract': 'across the curriculum. Through a step-by-step analysis it demonstrates how storytelling  techniques are congenial in teaching doctrine, skills, and ethics across the curriculum, whether'}, 'filled': False, 'gsrank': 2, 'pub_url': 'https://heinonline.org/hol-cgi-bin/get_pdf.cgi?handle=hein.journals/knust10&section=8', 'author_id': ['Oy3WeqoAAAAJ', '', ''], 'url_scholarbib': '/scholar?hl=en&q=info:zKx5NzswvwgJ:scholar.google.com/&output=cite&scirp=1&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=zKx5NzswvwgJ&ei=DIVoZuWOGLqY6rQP7_eJmAo&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:zKx5NzswvwgJ:scholar.google.com/&scioq=jules+elkins+2023+curriculum&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Translating Global Ideas: How Policy Legacies and Domestic Politics Shape Education Governance in Latin America', 'author': ['C Diaz-Rios'], 'pub_year': '2024', 'venue': 'NA', 'abstract': 'a centralized curriculum (centralized definition of curriculum contents), curricular autonomy  ( develop either parts of curriculum autonomously or the entire curriculum under very general'}, 'filled': False, 'gsrank': 3, 'pub_url': 'https://books.google.com/books?hl=en&lr=&id=MgXqEAAAQBAJ&oi=fnd&pg=PA1999&dq=jules+elkins+2023+curriculum&ots=ewMZxnitxz&sig=cOIe90Yy24EpEHPveVWM02HwJDY', 'author_id': ['UMR6lSIAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:-pccVMH-tggJ:scholar.google.com/&output=cite&scirp=2&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=-pccVMH-tggJ&ei=DIVoZuWOGLqY6rQP7_eJmAo&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:-pccVMH-tggJ:scholar.google.com/&scioq=jules+elkins+2023+curriculum&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Theatre History Studies 2022, Vol 41', 'author': ['L Milner', 'M Chapman', 'CE Mohler', 'T Boffone'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'Matthieu Chapman, Trevor Boffone, Samer Al- Saber, Jeanmarie Higgins, Alex Vermillion,  and Courtney Elkin Mohler are scholars whose work breathtakingly, and unapologetically,'}, 'filled': False, 'gsrank': 4, 'pub_url': 'https://books.google.com/books?hl=en&lr=&id=WLmeEAAAQBAJ&oi=fnd&pg=PR5&dq=jules+elkins+2023+curriculum&ots=kdEb6a1-yD&sig=RbA-JMyDjWD9a1AX3MS4h4Nbqrw', 'author_id': ['phYOjuYAAAAJ', 'zx9TiqEAAAAJ', '', 'wzEFYLgAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:7ki1egvOaqsJ:scholar.google.com/&output=cite&scirp=3&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=7ki1egvOaqsJ&ei=DIVoZuWOGLqY6rQP7_eJmAo&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:7ki1egvOaqsJ:scholar.google.com/&scioq=jules+elkins+2023+curriculum&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Agile objects', 'author': ['S German', 'J Harris'], 'pub_year': '2017', 'venue': 'Journal of Museum Education', 'abstract': 'This article discusses the selection of objects for teaching and outlines a curricular program,   In this vein, the work of James ElkinsFootnote 1 and Jules PrownFootnote 2 have been'}, 'filled': False, 'gsrank': 5, 'pub_url': 'https://www.tandfonline.com/doi/abs/10.1080/10598650.2017.1336369', 'author_id': ['IaU8Zt8AAAAJ', ''], 'url_scholarbib': '/scholar?hl=en&q=info:zKq0c9S-3t4J:scholar.google.com/&output=cite&scirp=4&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=zKq0c9S-3t4J&ei=DIVoZuWOGLqY6rQP7_eJmAo&json=', 'num_citations': 8, 'citedby_url': '/scholar?cites=16059483140933331660&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:zKq0c9S-3t4J:scholar.google.com/&scioq=jules+elkins+2023+curriculum&hl=en&as_sdt=0,33', 'eprint_url': 'https://ora.ox.ac.uk/objects/uuid:bbceeeeb-6d68-4337-8452-3b0d31388895/download_file?file_format=pdf&safe_filename=Agile%2Bobjects.pdf&type_of_work=Journal+article'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Bibliography of Narrative, A', 'author': ['JR Elkins'], 'pub_year': '1990', 'venue': 'J. Legal Educ.', 'abstract': 'A Bibliography of Narrative Page 1 A Bibliography of Narrative James R. Elkins The following  bibliography derives as much from afternoon reveries in favorite bookstores as from'}, 'filled': False, 'gsrank': 6, 'pub_url': 'https://heinonline.org/hol-cgi-bin/get_pdf.cgi?handle=hein.journals/jled40&section=20', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:Ky3SydkGLXEJ:scholar.google.com/&output=cite&scirp=5&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Djules%2Belkins%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=Ky3SydkGLXEJ&ei=DIVoZuWOGLqY6rQP7_eJmAo&json=', 'num_citations': 38, 'citedby_url': '/scholar?cites=8155182032701500715&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:Ky3SydkGLXEJ:scholar.google.com/&scioq=jules+elkins+2023+curriculum&hl=en&as_sdt=0,33'}
samy ayoub 2023 education
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
samy ayoub 2023 student
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Creativity in continuity: legal treatises (al-rasāʾil al-fiqhiyya) in Islamic law', 'author': ['S Ayoub'], 'pub_year': '2023', 'venue': 'Journal of Islamic Studies', 'abstract': 'This article explores how legal treatises (rasāʾil) were essential sites for the development  and expansion of Islamic legal schools’ (madhāhib) positions. The rasāʾil, along with legal'}, 'filled': False, 'gsrank': 1, 'pub_url': 'https://academic.oup.com/jis/article-abstract/34/3/305/6936671', 'author_id': ['_PROusgAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:syBe_r5Hh2AJ:scholar.google.com/&output=cite&scirp=0&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=syBe_r5Hh2AJ&ei=N4VoZoGRH43A6rQPjqSPmAY&json=', 'num_citations': 1, 'citedby_url': '/scholar?cites=6955607035133960371&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:syBe_r5Hh2AJ:scholar.google.com/&scioq=samy+ayoub+2023+student&hl=en&as_sdt=0,33', 'eprint_url': 'https://www.academia.edu/download/105087709/SAyoub_Creativity_in_Continuity_JIS.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'The Egyptian State as a Muǧtahid: Law and Religion in the Jurisprudence of the Egyptian Supreme Constitutional Court', 'author': ['S Ayoub'], 'pub_year': '2022', 'venue': 'Arab Law Quarterly', 'abstract': 'This article explores two recent decisions issued by the Egyptian Supreme Constitutional Court  (SCC) to demonstrate how the Court resolves conflicts involving Islamic and Christian law'}, 'filled': False, 'gsrank': 2, 'pub_url': 'https://brill.com/view/journals/alq/aop/article-10.1163-15730255-bja10119/article-10.1163-15730255-bja10119.xml', 'author_id': ['_PROusgAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:-HE7HaSSli0J:scholar.google.com/&output=cite&scirp=1&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=-HE7HaSSli0J&ei=N4VoZoGRH43A6rQPjqSPmAY&json=', 'num_citations': 2, 'citedby_url': '/scholar?cites=3284974211776082424&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:-HE7HaSSli0J:scholar.google.com/&scioq=samy+ayoub+2023+student&hl=en&as_sdt=0,33', 'eprint_url': 'https://www.academia.edu/download/88003741/SAyoub_Egyptian_SCC_ALQ_2022.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Law, Empire, and the Sultan: Ottoman Imperial Authority and Late Ḥanafī Jurisprudence. By Samy A. Ayoub', 'author': ['JE Baldwin'], 'pub_year': '2022', 'venue': 'NA', 'abstract': 'Ayoub  Ayoub shows how Ibn ʿĀbidīn combined theoretical recognition of the madhhab’s  traditional authority structure that gave primacy to the views of Abū Ḥanīfa and his students'}, 'filled': False, 'gsrank': 3, 'pub_url': 'https://academic.oup.com/jis/article-abstract/33/2/253/6456194', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:TpDo3rVskXYJ:scholar.google.com/&output=cite&scirp=2&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=TpDo3rVskXYJ&ei=N4VoZoGRH43A6rQPjqSPmAY&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:TpDo3rVskXYJ:scholar.google.com/&scioq=samy+ayoub+2023+student&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Ottoman Soldiers in the Arabian Peninsula: Fighting Armed Rebellion in the Sacred Mosque of Mecca in the Seventeenth Century', 'author': ['S Ayoub'], 'pub_year': '2018', 'venue': 'Turkish Historical Review', 'abstract': 'This article investigates how Hanafi jurists responded to armed rebellion against local  authorities in Mecca. I examine two understudied legal treatises that have been written about the'}, 'filled': False, 'gsrank': 4, 'pub_url': 'https://brill.com/view/journals/thr/9/1/article-p18_18.xml', 'author_id': ['_PROusgAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:UyfJSqVdKZ0J:scholar.google.com/&output=cite&scirp=3&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=UyfJSqVdKZ0J&ei=N4VoZoGRH43A6rQPjqSPmAY&json=', 'num_citations': 1, 'citedby_url': '/scholar?cites=11324685702505506643&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:UyfJSqVdKZ0J:scholar.google.com/&scioq=samy+ayoub+2023+student&hl=en&as_sdt=0,33', 'eprint_url': 'https://www.academia.edu/download/62252289/Ottoman_Soldiers_Ayoub20200302-84295-o21lfx.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Islamic education in contemporary Egypt: al-Azhar under al-Ṭayyib', 'author': ['A Omara'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'More than two million students in Egypt today receive their Islamic education through Al-  age-appropriate to middle and high school students. Additionally, my comparison shows the'}, 'filled': False, 'gsrank': 5, 'pub_url': 'https://repositories.lib.utexas.edu/items/8a9f75d7-2427-41c8-add1-e58426045f51', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:0Cc8iHXwiWYJ:scholar.google.com/&output=cite&scirp=4&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=0Cc8iHXwiWYJ&ei=N4VoZoGRH43A6rQPjqSPmAY&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:0Cc8iHXwiWYJ:scholar.google.com/&scioq=samy+ayoub+2023+student&hl=en&as_sdt=0,33', 'eprint_url': 'https://repositories.lib.utexas.edu/bitstreams/0bc53086-c471-4493-95c7-c7615b3f4bd5/download'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "Egypt's Plan for the Development of Historic Cairo and the Old Popular Neighborhoods", 'author': ['RR Sedky'], 'pub_year': '2023', 'venue': 'International Design Journal', 'abstract': 'Ayoub as a center for the development of handicrafts to preserve our heritage from  These  educational institutions encouraged students to learn more about and spread Islamic principles'}, 'filled': False, 'gsrank': 6, 'pub_url': 'https://idj.journals.ekb.eg/article_296279.html', 'author_id': ['q-t5Ln4AAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:6xjgvcJtx84J:scholar.google.com/&output=cite&scirp=5&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=6xjgvcJtx84J&ei=N4VoZoGRH43A6rQPjqSPmAY&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:6xjgvcJtx84J:scholar.google.com/&scioq=samy+ayoub+2023+student&hl=en&as_sdt=0,33', 'eprint_url': 'https://idj.journals.ekb.eg/article_296279_57326a830eb3cd61d8271275a7aa16c7.pdf'}
[{'title': 'Creativity in continuity: legal treatises (al-rasāʾil al-fiqhiyya) in Islamic law', 'author': ['S Ayoub'], 'year': '2023', 'abstract': 'This article explores how legal treatises (rasāʾil) were essential sites for the development  and expansion of Islamic legal schools’ (madhāhib) positions. The rasāʾil, along with legal', 'url': 'https://www.academia.edu/download/105087709/SAyoub_Creativity_in_Continuity_JIS.pdf'}]
samy ayoub 2023 classroom
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
samy ayoub 2023 curriculum
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Islamic education in contemporary Egypt: al-Azhar under al-Ṭayyib', 'author': ['A Omara'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'to al-Azhar Institutes’ curriculum introduced in 2013, namely, the  these modifications in the  fiqh curriculum? What were the topics  for curricular modification. However, did this make the'}, 'filled': False, 'gsrank': 1, 'pub_url': 'https://repositories.lib.utexas.edu/items/8a9f75d7-2427-41c8-add1-e58426045f51', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:0Cc8iHXwiWYJ:scholar.google.com/&output=cite&scirp=0&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=0Cc8iHXwiWYJ&ei=dYVoZo-rEPSz6rQP--ivkAo&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:0Cc8iHXwiWYJ:scholar.google.com/&scioq=samy+ayoub+2023+curriculum&hl=en&as_sdt=0,33', 'eprint_url': 'https://repositories.lib.utexas.edu/bitstreams/0bc53086-c471-4493-95c7-c7615b3f4bd5/download'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "Integrating Artificial Intelligence in a Morphology Course-An Analytical Study from University Students' Perspectives", 'author': ['NN Ayoub', 'NS Joudi', 'MSB Saba', 'ASB Saba'], 'pub_year': '2024', 'venue': 'ESI Preprints', 'abstract': 'took place on December 15 and December 22, 2023. All the participants have registered  in the morphology course for the academic year 2023-2024, third semester – second year.'}, 'filled': False, 'gsrank': 2, 'pub_url': 'https://esipreprints.org/index.php/esipreprints/article/view/1089', 'author_id': ['f4npzVwAAAAJ', '', '', ''], 'url_scholarbib': '/scholar?hl=en&q=info:enEbNXx0Mq4J:scholar.google.com/&output=cite&scirp=1&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=enEbNXx0Mq4J&ei=dYVoZo-rEPSz6rQP--ivkAo&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:enEbNXx0Mq4J:scholar.google.com/&scioq=samy+ayoub+2023+curriculum&hl=en&as_sdt=0,33', 'eprint_url': 'https://esipreprints.org/index.php/esipreprints/article/download/1089/1092'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Potent Roles of Humor in EFL Classes in Higher Education: An Exploratory Study of Lebanese Perspectives', 'author': ['NS Joudi', 'NN Ayoub'], 'pub_year': '2024', 'venue': 'ESI Preprints', 'abstract': '(2023) used the instructional humor processing theory to find out how different humor subtypes  are employed by teachers, such as course-related, course should be course-related since'}, 'filled': False, 'gsrank': 3, 'pub_url': 'https://esipreprints.org/index.php/esipreprints/article/view/987', 'author_id': ['', 'f4npzVwAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:z97AqgU0w9MJ:scholar.google.com/&output=cite&scirp=2&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=z97AqgU0w9MJ&ei=dYVoZo-rEPSz6rQP--ivkAo&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:z97AqgU0w9MJ:scholar.google.com/&scioq=samy+ayoub+2023+curriculum&hl=en&as_sdt=0,33', 'eprint_url': 'https://esipreprints.org/index.php/esipreprints/article/download/987/991'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Law, Empire, and the Sultan: Ottoman Imperial Authority and Late Ḥanafī Jurisprudence. By Samy A. Ayoub', 'author': ['JE Baldwin'], 'pub_year': '2022', 'venue': 'NA', 'abstract': 'Ayoub shows that  Ayoub’s critical engagement with the secondary literature also makes  the book, especially the chapter on the Mecelle, useful for advanced undergraduate courses'}, 'filled': False, 'gsrank': 4, 'pub_url': 'https://academic.oup.com/jis/article-abstract/33/2/253/6456194', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:TpDo3rVskXYJ:scholar.google.com/&output=cite&scirp=3&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=TpDo3rVskXYJ&ei=dYVoZo-rEPSz6rQP--ivkAo&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:TpDo3rVskXYJ:scholar.google.com/&scioq=samy+ayoub+2023+curriculum&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'What Follows the Fall? Investigating The Shifting Landscape of Political Violence in the Wake of Regime Breakdown', 'author': ['M Ayoub'], 'pub_year': '2024', 'venue': 'NA', 'abstract': 'While it is commonly argued the prior regime type influences regime breakdown outcomes  during contested transitions of power, the observed disparity between two countries with'}, 'filled': False, 'gsrank': 5, 'pub_url': 'https://fount.aucegypt.edu/etds/2320/', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:mE2wHAXaGBkJ:scholar.google.com/&output=cite&scirp=4&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=mE2wHAXaGBkJ&ei=dYVoZo-rEPSz6rQP--ivkAo&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:mE2wHAXaGBkJ:scholar.google.com/&scioq=samy+ayoub+2023+curriculum&hl=en&as_sdt=0,33', 'eprint_url': 'https://fount.aucegypt.edu/cgi/viewcontent.cgi?article=3362&context=etds'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'ONE NATION, ONE CURRICULUM An Ethnographic Account of Single National Curriculum (SNC)', 'author': ['S Ahmad'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'The National Commission on Education (Sharif Commission Report) of 1959 set up during  the Ayub regime suggested a liberal view of Islamic studies in the curriculum. The report'}, 'filled': False, 'gsrank': 6, 'pub_url': 'http://dspace.qau.edu.pk:8080/jspui/handle/123456789/28022', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:jYUH1m2HGrkJ:scholar.google.com/&output=cite&scirp=5&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dsamy%2Bayoub%2B2023%2Bcurriculum%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=jYUH1m2HGrkJ&ei=dYVoZo-rEPSz6rQP--ivkAo&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:jYUH1m2HGrkJ:scholar.google.com/&scioq=samy+ayoub+2023+curriculum&hl=en&as_sdt=0,33', 'eprint_url': 'http://dspace.qau.edu.pk:8080/jspui/bitstream/123456789/28022/1/ANT%202196.pdf'}
krishna kumar 2023 education
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
krishna kumar 2023 student
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'STUDENT PERFORMANCE INDICATOR USING MACHINE LEARNING', 'author': ['JR Kumar', 'BHS Kumar', 'SR Krishna', 'GV Teja'], 'pub_year': '2023', 'venue': 'NA', 'abstract': "This project centers on the development of a predictive model for forecasting students' academic performance using three regression algorithms: Linear Regression, Decision Tree Regressor, and Random Forest Regressor. Linear Regression, renowned for its simplicity and interpretability, assumes a linear association between input features and academic outcomes. In contrast, Decision Tree Regressor delineates complex, non-linear relationships by segmenting the feature space, albeit with a susceptibility to overfitting. On"}, 'filled': False, 'gsrank': 1, 'pub_url': 'https://tanzj.net/wp-content/uploads/2024/04/TJ-1575.pdf', 'author_id': ['b-SwjR0AAAAJ', '', '', ''], 'url_scholarbib': '/scholar?hl=en&q=info:XyE00jtC04oJ:scholar.google.com/&output=cite&scirp=0&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dkrishna%2Bkumar%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=XyE00jtC04oJ&ei=rIVoZsjPB43A6rQPjqSPmAY&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:XyE00jtC04oJ:scholar.google.com/&scioq=krishna+kumar+2023+student&hl=en&as_sdt=0,33', 'eprint_url': 'https://tanzj.net/wp-content/uploads/2024/04/TJ-1575.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Unified Forecast System Student Engagement Plan', 'author': ['A Srinivasan', 'J Vogt', 'M Huang', 'K Kumar', 'N Jacobs'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'The position of the UFS Student Ambassador was designed with the intention of creating a UFS Student Engagement Plan that highlights suggestions for closing the gap between the UFS and academia. The Student Ambassador will advocate for community engagement and technological advancements for academia while providing an undergraduate student perspective on typical academic curriculums and experiences as a meteorology and atmospheric science student. They will perform innovative methods of outreach to academia'}, 'filled': False, 'gsrank': 2, 'pub_url': 'https://repository.library.noaa.gov/view/noaa/56168', 'author_id': ['', '', 'f36ybskAAAAJ', 'T0TnjkQAAAAJ', ''], 'url_scholarbib': '/scholar?hl=en&q=info:o8rv2OqGqFYJ:scholar.google.com/&output=cite&scirp=1&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dkrishna%2Bkumar%2B2023%2Bstudent%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=o8rv2OqGqFYJ&ei=rIVoZsjPB43A6rQPjqSPmAY&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:o8rv2OqGqFYJ:scholar.google.com/&scioq=krishna+kumar+2023+student&hl=en&as_sdt=0,33', 'eprint_url': 'https://repository.library.noaa.gov/view/noaa/56168/noaa_56168_DS1.pdf'}
[{'title': 'STUDENT PERFORMANCE INDICATOR USING MACHINE LEARNING', 'author': ['JR Kumar', 'BHS Kumar', 'SR Krishna', 'GV Teja'], 'year': '2023', 'abstract': "This project centers on the development of a predictive model for forecasting students' academic performance using three regression algorithms: Linear Regression, Decision Tree Regressor, and Random Forest Regressor. Linear Regression, renowned for its simplicity and interpretability, assumes a linear association between input features and academic outcomes. In contrast, Decision Tree Regressor delineates complex, non-linear relationships by segmenting the feature space, albeit with a susceptibility to overfitting. On", 'url': 'https://tanzj.net/wp-content/uploads/2024/04/TJ-1575.pdf'}]
[{'title': 'STUDENT PERFORMANCE INDICATOR USING MACHINE LEARNING', 'author': ['JR Kumar', 'BHS Kumar', 'SR Krishna', 'GV Teja'], 'year': '2023', 'abstract': "This project centers on the development of a predictive model for forecasting students' academic performance using three regression algorithms: Linear Regression, Decision Tree Regressor, and Random Forest Regressor. Linear Regression, renowned for its simplicity and interpretability, assumes a linear association between input features and academic outcomes. In contrast, Decision Tree Regressor delineates complex, non-linear relationships by segmenting the feature space, albeit with a susceptibility to overfitting. On", 'url': 'https://tanzj.net/wp-content/uploads/2024/04/TJ-1575.pdf'}, {'title': 'Unified Forecast System Student Engagement Plan', 'author': ['A Srinivasan', 'J Vogt', 'M Huang', 'K Kumar', 'N Jacobs'], 'year': '2023', 'abstract': 'The position of the UFS Student Ambassador was designed with the intention of creating a UFS Student Engagement Plan that highlights suggestions for closing the gap between the UFS and academia. The Student Ambassador will advocate for community engagement and technological advancements for academia while providing an undergraduate student perspective on typical academic curriculums and experiences as a meteorology and atmospheric science student. They will perform innovative methods of outreach to academia', 'url': 'https://repository.library.noaa.gov/view/noaa/56168/noaa_56168_DS1.pdf'}]
krishna kumar 2023 classroom
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
layla guyot 2023 education
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "Elementary school teachers' noticing of essential mathematical reasoning forms: Justification and generalization", 'author': ['K Melhuish', 'E Thanheiser', 'L Guyot'], 'pub_year': '2020', 'venue': '… of Mathematics Teacher Education', 'abstract': 'in terms of mathematical content and reasoning form, we found that teachers rarely  attended to justifying and generalizing in a manner consistent with the mathematics education'}, 'filled': False, 'gsrank': 1, 'pub_url': 'https://link.springer.com/article/10.1007/s10857-018-9408-4', 'author_id': ['', '7nyympkAAAAJ', ''], 'url_scholarbib': '/scholar?hl=en&q=info:bFdYdONMBNQJ:scholar.google.com/&output=cite&scirp=0&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dlayla%2Bguyot%2B2023%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=bFdYdONMBNQJ&ei=1IVoZoXEFa6p6rQPit2GkAE&json=', 'num_citations': 56, 'citedby_url': '/scholar?cites=15277420375740798828&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:bFdYdONMBNQJ:scholar.google.com/&scioq=layla+guyot+2023+education&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Effect of manipulative-based interventions on improving mathematics computation outcomes for students with mathematics difficulties', 'author': ['Z Shen'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'populations of students special education teachers and general education teachers work   smaller than those of researcher implemented studies and special education implemented'}, 'filled': False, 'gsrank': 2, 'pub_url': 'https://repositories.lib.utexas.edu/items/7f225ad9-5d02-4b45-97ec-099acbb6cd10', 'author_id': ['YKt7s3AAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:zAhWWgaq2FkJ:scholar.google.com/&output=cite&scirp=1&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dlayla%2Bguyot%2B2023%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=zAhWWgaq2FkJ&ei=1IVoZoXEFa6p6rQPit2GkAE&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:zAhWWgaq2FkJ:scholar.google.com/&scioq=layla+guyot+2023+education&hl=en&as_sdt=0,33', 'eprint_url': 'https://repositories.lib.utexas.edu/bitstreams/4bed7143-7d75-44cb-881d-6a557ab30fa4/download'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "Developing measures of teachers' mathematics knowledge for teaching", 'author': ['HC Hill', 'SG Schilling', 'DL Ball'], 'pub_year': '2004', 'venue': 'The elementary school …', 'abstract': 'In this article we discuss efforts to design and empirically test measures of teachers’ content  knowledge for teaching elementary mathematics. We begin by reviewing the literature on'}, 'filled': False, 'gsrank': 3, 'pub_url': 'https://www.journals.uchicago.edu/doi/abs/10.1086/428763', 'author_id': ['0uZHioAAAAAJ', 'OMpk2GgAAAAJ', 'qdho5P0AAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:8EMspcbfbm8J:scholar.google.com/&output=cite&scirp=2&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dlayla%2Bguyot%2B2023%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=8EMspcbfbm8J&ei=1IVoZoXEFa6p6rQPit2GkAE&json=', 'num_citations': 1775, 'citedby_url': '/scholar?cites=8029601229915833328&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:8EMspcbfbm8J:scholar.google.com/&scioq=layla+guyot+2023+education&hl=en&as_sdt=0,33', 'eprint_url': 'https://sii.soe.umich.edu/newsite_dev/documents/hill_schill_ball.db.r59E46.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "Mapping variation in children's mathematical reasoning: the case of 'what else belongs?'", 'author': ['C Vale', 'W Widjaja', 'S Herbert', 'LA Bragg'], 'pub_year': '2017', 'venue': '… Mathematics Education', 'abstract': 'Chinnappan (Eds.), Proceedings of the 29th annual conference of the mathematics  education research group of Australasia (pp. 301–308). Adelaide, Australia: MERGA.'}, 'filled': False, 'gsrank': 4, 'pub_url': 'https://link.springer.com/article/10.1007/s10763-016-9725-y', 'author_id': ['1mefKe0AAAAJ', 'ZCXnJOAAAAAJ', 'SjFwWEUAAAAJ', 'a_XGxmoAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:74E6hZu-c5EJ:scholar.google.com/&output=cite&scirp=3&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dlayla%2Bguyot%2B2023%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=74E6hZu-c5EJ&ei=1IVoZoXEFa6p6rQPit2GkAE&json=', 'num_citations': 40, 'citedby_url': '/scholar?cites=10480930332985688559&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:74E6hZu-c5EJ:scholar.google.com/&scioq=layla+guyot+2023+education&hl=en&as_sdt=0,33', 'eprint_url': 'https://www.researchgate.net/profile/Wanty-Widjaja/publication/296627284_Mapping_Variation_in_Children%27s_Mathematical_Reasoning_The_Case_of_%27What_Else_Belongs%27/links/56f3817908ae81582bebb6a0/Mapping-Variation-in-Childrens-Mathematical-Reasoning-The-Case-of-What-Else-Belongs.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Centering Justice in Conservation Solutions for People and Nature', 'author': ['KE Langhans'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'and test equipment and hike in the best biological preserve ever, especially Jorge Ramos  for being a great mentor and friend, and for doing so much to improve equity and education in'}, 'filled': False, 'gsrank': 5, 'pub_url': 'https://search.proquest.com/openview/e5642bf3919d086e28ae3d0634014cee/1?pq-origsite=gscholar&cbl=18750&diss=y', 'author_id': ['z39ki-gAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:TBvIU0tQqWEJ:scholar.google.com/&output=cite&scirp=4&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dlayla%2Bguyot%2B2023%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=TBvIU0tQqWEJ&ei=1IVoZoXEFa6p6rQPit2GkAE&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:TBvIU0tQqWEJ:scholar.google.com/&scioq=layla+guyot+2023+education&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'The Struggle of Struggles', 'author': ['V Pigee'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'Another Delta native, Layla Young, who auditioned for the play and was cast as Wilma  Our  next goal was to buy a new car and complete my education. Paul kept his promise to educate'}, 'filled': False, 'gsrank': 6, 'pub_url': 'https://books.google.com/books?hl=en&lr=&id=vkytEAAAQBAJ&oi=fnd&pg=PP1&dq=layla+guyot+2023+education&ots=vzLcFlSTyQ&sig=NLhIC5qLCzH_VRNuz3p27HTX0bA', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:aZFH7nlkEyAJ:scholar.google.com/&output=cite&scirp=5&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dlayla%2Bguyot%2B2023%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=aZFH7nlkEyAJ&ei=1IVoZoXEFa6p6rQPit2GkAE&json=', 'num_citations': 7, 'citedby_url': '/scholar?cites=2311301508622684521&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:aZFH7nlkEyAJ:scholar.google.com/&scioq=layla+guyot+2023+education&hl=en&as_sdt=0,33'}
layla guyot 2023 student
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
layla guyot 2023 classroom
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "Elementary school teachers' noticing of essential mathematical reasoning forms: Justification and generalization", 'author': ['K Melhuish', 'E Thanheiser', 'L Guyot'], 'pub_year': '2020', 'venue': 'Journal of Mathematics Teacher …', 'abstract': 'noticing justifying and generalizing in their own classrooms and the levels researchers  observed in two consecutive lessons in those classrooms, we found significant discrepancies. In'}, 'filled': False, 'gsrank': 1, 'pub_url': 'https://link.springer.com/article/10.1007/s10857-018-9408-4', 'author_id': ['', '7nyympkAAAAJ', ''], 'url_scholarbib': '/scholar?hl=en&q=info:bFdYdONMBNQJ:scholar.google.com/&output=cite&scirp=0&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dlayla%2Bguyot%2B2023%2Bclassroom%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=bFdYdONMBNQJ&ei=AoZoZsSDMJ--6rQP8OOGwAY&json=', 'num_citations': 56, 'citedby_url': '/scholar?cites=15277420375740798828&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:bFdYdONMBNQJ:scholar.google.com/&scioq=layla+guyot+2023+classroom&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "Mapping variation in children's mathematical reasoning: the case of 'what else belongs?'", 'author': ['C Vale', 'W Widjaja', 'S Herbert', 'LA Bragg'], 'pub_year': '2017', 'venue': 'International Journal of …', 'abstract': 'One video-camera was used in the Canadian classroom where one author taught the lesson  , another student or materials available in the classroom such as multiplication fact posters.'}, 'filled': False, 'gsrank': 2, 'pub_url': 'https://link.springer.com/article/10.1007/s10763-016-9725-y', 'author_id': ['1mefKe0AAAAJ', 'ZCXnJOAAAAAJ', 'SjFwWEUAAAAJ', 'a_XGxmoAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:74E6hZu-c5EJ:scholar.google.com/&output=cite&scirp=1&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dlayla%2Bguyot%2B2023%2Bclassroom%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=74E6hZu-c5EJ&ei=AoZoZsSDMJ--6rQP8OOGwAY&json=', 'num_citations': 40, 'citedby_url': '/scholar?cites=10480930332985688559&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:74E6hZu-c5EJ:scholar.google.com/&scioq=layla+guyot+2023+classroom&hl=en&as_sdt=0,33', 'eprint_url': 'https://www.researchgate.net/profile/Wanty-Widjaja/publication/296627284_Mapping_Variation_in_Children%27s_Mathematical_Reasoning_The_Case_of_%27What_Else_Belongs%27/links/56f3817908ae81582bebb6a0/Mapping-Variation-in-Childrens-Mathematical-Reasoning-The-Case-of-What-Else-Belongs.pdf'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'The Struggle of Struggles', 'author': ['V Pigee'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'A former teacher invited me into her classroom, where I learned of students’ grandparents  involved in activities in the 1960s. I found Mrs. Pigee after conducting quite a few interviews in'}, 'filled': False, 'gsrank': 3, 'pub_url': 'https://books.google.com/books?hl=en&lr=&id=vkytEAAAQBAJ&oi=fnd&pg=PP1&dq=layla+guyot+2023+classroom&ots=vzLcFlSTDM&sig=zRL67hq0bb1ki2D28csmVqSm3_0', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:aZFH7nlkEyAJ:scholar.google.com/&output=cite&scirp=2&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dlayla%2Bguyot%2B2023%2Bclassroom%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=aZFH7nlkEyAJ&ei=AoZoZsSDMJ--6rQP8OOGwAY&json=', 'num_citations': 7, 'citedby_url': '/scholar?cites=2311301508622684521&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:aZFH7nlkEyAJ:scholar.google.com/&scioq=layla+guyot+2023+classroom&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "Developing measures of teachers' mathematics knowledge for teaching", 'author': ['HC Hill', 'SG Schilling', 'DL Ball'], 'pub_year': '2004', 'venue': 'The elementary school …', 'abstract': 'Other items, however, appear to be based on the ways mathematics arises in elementary  classrooms, or on what we call specialized knowledge of content (SKC), including building or'}, 'filled': False, 'gsrank': 4, 'pub_url': 'https://www.journals.uchicago.edu/doi/abs/10.1086/428763', 'author_id': ['0uZHioAAAAAJ', 'OMpk2GgAAAAJ', 'qdho5P0AAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:8EMspcbfbm8J:scholar.google.com/&output=cite&scirp=3&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dlayla%2Bguyot%2B2023%2Bclassroom%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=8EMspcbfbm8J&ei=AoZoZsSDMJ--6rQP8OOGwAY&json=', 'num_citations': 1775, 'citedby_url': '/scholar?cites=8029601229915833328&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:8EMspcbfbm8J:scholar.google.com/&scioq=layla+guyot+2023+classroom&hl=en&as_sdt=0,33', 'eprint_url': 'https://sii.soe.umich.edu/newsite_dev/documents/hill_schill_ball.db.r59E46.pdf'}
layla guyot 2023 curriculum
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
matt bowers 2022 education
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': '“Why Do I Have to Learn This Anyway?”: A Qualitative Investigative Action Research Study Into the Tension Between the Rural, Working-Class Masculine Student and …', 'author': ['JM Bowers'], 'pub_year': '2022', 'venue': 'NA', 'abstract': 'The specific problem of practice on which this study was focused is the tension experienced  between the rural (National Center for Education Statistics, 2016), working-class (Draut,'}, 'filled': False, 'gsrank': 1, 'pub_url': 'https://search.proquest.com/openview/e845ed52da4d1b1520742b5ef416eff9/1?pq-origsite=gscholar&cbl=18750&diss=y', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:DKPd88FYz2wJ:scholar.google.com/&output=cite&scirp=0&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=DKPd88FYz2wJ&ei=OoZoZo3DLIaM6rQPpe-zqAs&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:DKPd88FYz2wJ:scholar.google.com/&scioq=matt+bowers+2022+education&hl=en&as_sdt=0,33', 'eprint_url': 'https://scholarcommons.sc.edu/cgi/viewcontent.cgi?article=7672&context=etd'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'School-wide Academic Outcomes and Instructional Modality Used During the 2018-2022 School Years', 'author': ['MA Bowser'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'utilized by public schools during the 2019-2022 school years. This study also determined if   a school during the 2020-2021 and 2021-2022 school years and the school-wide academic'}, 'filled': False, 'gsrank': 2, 'pub_url': 'https://search.proquest.com/openview/2812ee3e3b152f4cdab0458a8ce56b24/1?pq-origsite=gscholar&cbl=18750&diss=y', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:2EQn5BmoUUkJ:scholar.google.com/&output=cite&scirp=1&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=2EQn5BmoUUkJ&ei=OoZoZo3DLIaM6rQPpe-zqAs&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:2EQn5BmoUUkJ:scholar.google.com/&scioq=matt+bowers+2022+education&hl=en&as_sdt=0,33', 'eprint_url': 'https://dc.etsu.edu/cgi/viewcontent.cgi?article=5754&context=etd'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "A Mathematics Educator Walks into a Physics Class: Identifying Math Skills in Students' Physics Problem-Solving Practices", 'author': ['J Bowers', 'M Anderson', 'K Beckhard'], 'pub_year': '2023', 'venue': 'Journal for STEM Education …', 'abstract': 'Practice—augmented by the Next Generation Science Standards (National Research  Council, 2013), the CRAFTY workshop notes (Cummings & Emery, 2004), and other educational'}, 'filled': False, 'gsrank': 3, 'pub_url': 'https://link.springer.com/article/10.1007/s41979-023-00105-w', 'author_id': ['736vORkAAAAJ', 'u1pGFx4AAAAJ', ''], 'url_scholarbib': '/scholar?hl=en&q=info:gdxsWnycXiEJ:scholar.google.com/&output=cite&scirp=2&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=gdxsWnycXiEJ&ei=OoZoZo3DLIaM6rQPpe-zqAs&json=', 'num_citations': 1, 'citedby_url': '/scholar?cites=2404531308969385089&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:gdxsWnycXiEJ:scholar.google.com/&scioq=matt+bowers+2022+education&hl=en&as_sdt=0,33', 'eprint_url': 'https://link.springer.com/article/10.1007/s41979-023-00105-w'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "Teachers' Employment Contracts: Unjust Salaries and Unconscionable Terms", 'author': ['N Bowers'], 'pub_year': '2023', 'venue': 'W. Mich. U. Cooley L. Rev.', 'abstract': 'those similarly educated make, it  2022, the National Education Association reported that  teachers often had to double their class sizes and that schools could not offer special education'}, 'filled': False, 'gsrank': 4, 'pub_url': 'https://heinonline.org/hol-cgi-bin/get_pdf.cgi?handle=hein.journals/tmclr38&section=19', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:gpyPqaesmwIJ:scholar.google.com/&output=cite&scirp=3&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=gpyPqaesmwIJ&ei=OoZoZo3DLIaM6rQPpe-zqAs&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:gpyPqaesmwIJ:scholar.google.com/&scioq=matt+bowers+2022+education&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'Learning design for holistic student formation', 'author': ['D Hockridge', 'M Bower'], 'pub_year': '2023', 'venue': 'Distance Education', 'abstract': 'modalities of educational technologies might influence different domains of learning of  relevance to formation, such as the affective or conative domains could be fruitful (Bower, Citation'}, 'filled': False, 'gsrank': 5, 'pub_url': 'https://www.tandfonline.com/doi/abs/10.1080/01587919.2023.2198484', 'author_id': ['Xhe9Z5kAAAAJ', 'p_md3-sAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:bOq7jETostoJ:scholar.google.com/&output=cite&scirp=4&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=bOq7jETostoJ&ei=OoZoZo3DLIaM6rQPpe-zqAs&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:bOq7jETostoJ:scholar.google.com/&scioq=matt+bowers+2022+education&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "How remote learning impacted elementary students' online self-regulation for learning: A COVID-19 natural experiment", 'author': ['J Torrington', 'M Bower', 'EC Burns'], 'pub_year': '2023', 'venue': 'Education and Information …', 'abstract': 'Self-regulated learning (aka, self-regulation for learning; SRL) is a well-established and  defined construct situated within educational psychology that has been widely researched since'}, 'filled': False, 'gsrank': 6, 'pub_url': 'https://link.springer.com/article/10.1007/s10639-023-12352-w', 'author_id': ['GlOL82cAAAAJ', 'p_md3-sAAAAJ', 'ShQ95xsAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:aZZZ_S-cx0gJ:scholar.google.com/&output=cite&scirp=5&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Beducation%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=aZZZ_S-cx0gJ&ei=OoZoZo3DLIaM6rQPpe-zqAs&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:aZZZ_S-cx0gJ:scholar.google.com/&scioq=matt+bowers+2022+education&hl=en&as_sdt=0,33'}
[{'title': '“Why Do I Have to Learn This Anyway?”: A Qualitative Investigative Action Research Study Into the Tension Between the Rural, Working-Class Masculine Student and …', 'author': ['JM Bowers'], 'year': '2022', 'abstract': 'The specific problem of practice on which this study was focused is the tension experienced  between the rural (National Center for Education Statistics, 2016), working-class (Draut,', 'url': 'https://scholarcommons.sc.edu/cgi/viewcontent.cgi?article=7672&context=etd'}]
matt bowers 2022 student
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
matt bowers 2022 classroom
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': '“Why Do I Have to Learn This Anyway?”: A Qualitative Investigative Action Research Study Into the Tension Between the Rural, Working-Class Masculine Student and …', 'author': ['JM Bowers'], 'pub_year': '2022', 'venue': 'NA', 'abstract': 'This study was conducted partly through an English IV College Prep classroom composed of   The study was also conducted outside of the English IV College Prep classroom through a'}, 'filled': False, 'gsrank': 1, 'pub_url': 'https://search.proquest.com/openview/e845ed52da4d1b1520742b5ef416eff9/1?pq-origsite=gscholar&cbl=18750&diss=y', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:DKPd88FYz2wJ:scholar.google.com/&output=cite&scirp=0&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Bclassroom%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=DKPd88FYz2wJ&ei=cIZoZp-JN4aM6rQPpe-zqAs&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:DKPd88FYz2wJ:scholar.google.com/&scioq=matt+bowers+2022+classroom&hl=en&as_sdt=0,33', 'eprint_url': 'https://scholarcommons.sc.edu/cgi/viewcontent.cgi?article=7672&context=etd'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "A Mathematics Educator Walks into a Physics Class: Identifying Math Skills in Students' Physics Problem-Solving Practices", 'author': ['J Bowers', 'M Anderson', 'K Beckhard'], 'pub_year': '2023', 'venue': 'Journal for STEM Education …', 'abstract': 'Although the context for this study was a physics classroom, we believe that the framework  for  to the instructor regarding the types of practices that are negotiated in the classroom.'}, 'filled': False, 'gsrank': 2, 'pub_url': 'https://link.springer.com/article/10.1007/s41979-023-00105-w', 'author_id': ['736vORkAAAAJ', 'u1pGFx4AAAAJ', ''], 'url_scholarbib': '/scholar?hl=en&q=info:gdxsWnycXiEJ:scholar.google.com/&output=cite&scirp=1&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Bclassroom%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=gdxsWnycXiEJ&ei=cIZoZp-JN4aM6rQPpe-zqAs&json=', 'num_citations': 1, 'citedby_url': '/scholar?cites=2404531308969385089&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:gdxsWnycXiEJ:scholar.google.com/&scioq=matt+bowers+2022+classroom&hl=en&as_sdt=0,33', 'eprint_url': 'https://link.springer.com/article/10.1007/s41979-023-00105-w'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'School-wide Academic Outcomes and Instructional Modality Used During the 2018-2022 School Years', 'author': ['MA Bowser'], 'pub_year': '2023', 'venue': 'NA', 'abstract': 'utilized by public schools during the 2019-2022 school years. This study also determined if   a school during the 2020-2021 and 2021-2022 school years and the school-wide academic'}, 'filled': False, 'gsrank': 3, 'pub_url': 'https://search.proquest.com/openview/2812ee3e3b152f4cdab0458a8ce56b24/1?pq-origsite=gscholar&cbl=18750&diss=y', 'author_id': [''], 'url_scholarbib': '/scholar?hl=en&q=info:2EQn5BmoUUkJ:scholar.google.com/&output=cite&scirp=2&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Bclassroom%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=2EQn5BmoUUkJ&ei=cIZoZp-JN4aM6rQPpe-zqAs&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:2EQn5BmoUUkJ:scholar.google.com/&scioq=matt+bowers+2022+classroom&hl=en&as_sdt=0,33', 'eprint_url': 'https://dc.etsu.edu/cgi/viewcontent.cgi?article=5754&context=etd'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "How remote learning impacted elementary students' online self-regulation for learning: A COVID-19 natural experiment", 'author': ['J Torrington', 'M Bower', 'EC Burns'], 'pub_year': '2023', 'venue': 'Education and Information …', 'abstract': 'As such, this study replicated the methodology used by the authors in the original regular  classroom (Time 1) study completed in Term 1, 2021, to ensure comparability and fidelity. The'}, 'filled': False, 'gsrank': 4, 'pub_url': 'https://link.springer.com/article/10.1007/s10639-023-12352-w', 'author_id': ['GlOL82cAAAAJ', 'p_md3-sAAAAJ', 'ShQ95xsAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:aZZZ_S-cx0gJ:scholar.google.com/&output=cite&scirp=3&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Bclassroom%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=aZZZ_S-cx0gJ&ei=cIZoZp-JN4aM6rQPpe-zqAs&json=', 'num_citations': 0, 'url_related_articles': '/scholar?q=related:aZZZ_S-cx0gJ:scholar.google.com/&scioq=matt+bowers+2022+classroom&hl=en&as_sdt=0,33'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': 'What self-regulation strategies do elementary students utilize while learning online?', 'author': ['J Torrington', 'M Bower', 'EC Burns'], 'pub_year': '2023', 'venue': 'Education and Information …', 'abstract': 'with the database and how to access it because it is used regularly in classroom activities.   and therefore explicitly taught in elementary school classrooms (for example: planning when'}, 'filled': False, 'gsrank': 5, 'pub_url': 'https://link.springer.com/article/10.1007/s10639-022-11244-9', 'author_id': ['GlOL82cAAAAJ', 'p_md3-sAAAAJ', 'ShQ95xsAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:HUdVtdSCVhgJ:scholar.google.com/&output=cite&scirp=4&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Bclassroom%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=HUdVtdSCVhgJ&ei=cIZoZp-JN4aM6rQPpe-zqAs&json=', 'num_citations': 6, 'citedby_url': '/scholar?cites=1753732954994329373&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:HUdVtdSCVhgJ:scholar.google.com/&scioq=matt+bowers+2022+classroom&hl=en&as_sdt=0,33', 'eprint_url': 'https://link.springer.com/article/10.1007/s10639-022-11244-9'}
{'container_type': 'Publication', 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'>, 'bib': {'title': "Elementary students' self‐regulation in computer‐based learning environments: How do self‐report measures, observations and teacher rating relate to task …", 'author': ['J Torrington', 'M Bower', 'EC Burns'], 'pub_year': '2024', 'venue': 'British Journal of …', 'abstract': 'Given the increasing emphasis of computer-based learning within elementary classrooms  (OECD, 2020a; NSW Education Standards Authority, 2021b), understanding these'}, 'filled': False, 'gsrank': 6, 'pub_url': 'https://bera-journals.onlinelibrary.wiley.com/doi/abs/10.1111/bjet.13338', 'author_id': ['GlOL82cAAAAJ', 'p_md3-sAAAAJ', 'ShQ95xsAAAAJ'], 'url_scholarbib': '/scholar?hl=en&q=info:Y68t_Y4aY4AJ:scholar.google.com/&output=cite&scirp=5&hl=en', 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3Dmatt%2Bbowers%2B2022%2Bclassroom%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=Y68t_Y4aY4AJ&ei=cIZoZp-JN4aM6rQPpe-zqAs&json=', 'num_citations': 5, 'citedby_url': '/scholar?cites=9251267260984438627&as_sdt=5,33&sciodt=0,33&hl=en', 'url_related_articles': '/scholar?q=related:Y68t_Y4aY4AJ:scholar.google.com/&scioq=matt+bowers+2022+classroom&hl=en&as_sdt=0,33', 'eprint_url': 'https://bera-journals.onlinelibrary.wiley.com/doi/full/10.1111/bjet.13338'}
[{'title': '“Why Do I Have to Learn This Anyway?”: A Qualitative Investigative Action Research Study Into the Tension Between the Rural, Working-Class Masculine Student and …', 'author': ['JM Bowers'], 'year': '2022', 'abstract': 'This study was conducted partly through an English IV College Prep classroom composed of   The study was also conducted outside of the English IV College Prep classroom through a', 'url': 'https://scholarcommons.sc.edu/cgi/viewcontent.cgi?article=7672&context=etd'}]
matt bowers 2022 curriculum
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
{
  "title": "Reflections on Teaching an Engineering Course through Murder Mysteries.",
  "author": [
    "K Kumar"
  ],
  "year": "2023",
  "abstract": "This paper presents a reflective analysis of a novel approach to Problem-Based Learning (PBL)  to teach abstract concepts in a large-class setting, specifically tailored for a third-year",
  "url": "https://files.eric.ed.gov/fulltext/EJ1407522.pdf"
}
{
  "title": "Developmental challenges to internationalizing the higher education sector: a critical inquiry of business schools in Kerala",
  "author": [
    "KT John",
    "KS Kumar"
  ],
  "year": "2023",
  "abstract": "Purpose Kerala is one of India's most advanced states in human development and other  social indices. This study aims to look at the management education scenario in Kerala from a",
  "url": "https://www.emerald.com/insight/content/doi/10.1108/RAMJ-07-2021-0058/full/html"
}
{
  "title": "Creativity in continuity: legal treatises (al-ras\u0101\u02beil al-fiqhiyya) in Islamic law",
  "author": [
    "S Ayoub"
  ],
  "year": "2023",
  "abstract": "This article explores how legal treatises (ras\u0101\u02beil) were essential sites for the development  and expansion of Islamic legal schools\u2019 (madh\u0101hib) positions. The ras\u0101\u02beil, along with legal",
  "url": "https://www.academia.edu/download/105087709/SAyoub_Creativity_in_Continuity_JIS.pdf"
}
{
  "title": "STUDENT PERFORMANCE INDICATOR USING MACHINE LEARNING",
  "author": [
    "JR Kumar",
    "BHS Kumar",
    "SR Krishna",
    "GV Teja"
  ],
  "year": "2023",
  "abstract": "This project centers on the development of a predictive model for forecasting students' academic performance using three regression algorithms: Linear Regression, Decision Tree Regressor, and Random Forest Regressor. Linear Regression, renowned for its simplicity and interpretability, assumes a linear association between input features and academic outcomes. In contrast, Decision Tree Regressor delineates complex, non-linear relationships by segmenting the feature space, albeit with a susceptibility to overfitting. On",
  "url": "https://tanzj.net/wp-content/uploads/2024/04/TJ-1575.pdf"
}
{
  "title": "Unified Forecast System Student Engagement Plan",
  "author": [
    "A Srinivasan",
    "J Vogt",
    "M Huang",
    "K Kumar",
    "N Jacobs"
  ],
  "year": "2023",
  "abstract": "The position of the UFS Student Ambassador was designed with the intention of creating a UFS Student Engagement Plan that highlights suggestions for closing the gap between the UFS and academia. The Student Ambassador will advocate for community engagement and technological advancements for academia while providing an undergraduate student perspective on typical academic curriculums and experiences as a meteorology and atmospheric science student. They will perform innovative methods of outreach to academia",
  "url": "https://repository.library.noaa.gov/view/noaa/56168/noaa_56168_DS1.pdf"
}
{
  "title": "\u201cWhy Do I Have to Learn This Anyway?\u201d: A Qualitative Investigative Action Research Study Into the Tension Between the Rural, Working-Class Masculine Student and \u2026",
  "author": [
    "JM Bowers"
  ],
  "year": "2022",
  "abstract": "The specific problem of practice on which this study was focused is the tension experienced  between the rural (National Center for Education Statistics, 2016), working-class (Draut,",
  "url": "https://scholarcommons.sc.edu/cgi/viewcontent.cgi?article=7672&context=etd"
}
{
  "title": "\u201cWhy Do I Have to Learn This Anyway?\u201d: A Qualitative Investigative Action Research Study Into the Tension Between the Rural, Working-Class Masculine Student and \u2026",
  "author": [
    "JM Bowers"
  ],
  "year": "2022",
  "abstract": "This study was conducted partly through an English IV College Prep classroom composed of   The study was also conducted outside of the English IV College Prep classroom through a",
  "url": "https://scholarcommons.sc.edu/cgi/viewcontent.cgi?article=7672&context=etd"
}
(base) tanushkaushik@Tanushs-MacBook-Pro Texas Lead DS % 
