(base) tanushkaushik@Tanushs-MacBook-Pro Texas Lead DS % python3 testedscholarlymodule2.py
krishna kumar 2023 curriculum
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
jules elkins 2023 education
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
jules elkins 2023 student
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
jules elkins 2023 classroom
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
jules elkins 2023 curriculum
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
samy ayoub 2023 education
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
samy ayoub 2023 student
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
samy ayoub 2023 classroom
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
samy ayoub 2023 curriculum
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
krishna kumar 2023 education
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
krishna kumar 2023 student
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
krishna kumar 2023 classroom
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
layla guyot 2023 education
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
layla guyot 2023 student
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
layla guyot 2023 classroom
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
layla guyot 2023 curriculum
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
matt bowers 2022 education
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
matt bowers 2022 student
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
matt bowers 2022 classroom
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
matt bowers 2022 curriculum
Attempt 1/1 failed with error: Cannot Fetch from Google Scholar.. Reinitializing proxy and retrying...
(base) tanushkaushik@Tanushs-MacBook-Pro Texas Lead DS % 















